### ISSUE TITLE
emacs-24.4-mac-5.2 pen icon missing

### ISSUE THREAD

**Issue by wyuenho** [railwaycat/emacs-mac-port#77]
FYI

**Comment by railwaycat** [comment]
Hmm...it seems OK on my side

Could you please give me the output of this command?

```
ls -l /Applications/Emacs.app/Contents/Resources/*icns*
```

`/Applications/Emacs.app` is where you put emacs-mac-port app. 

Thanks!

**Comment by wyuenho** [comment]
That's not a pen icon, that's still the Gnu ox.

Bounced from an umbrella

**Comment by railwaycat** [comment]
Icon of Emacs.app decided by the symbolic link to `Emacs.app/Contents/Resources/Emacs.icns`. If it pointing to `Emacs.icns.official` then the "pen icon" should shows up (you could check it by the command in my previous comment), otherwise I will suspect if it's a cache of Finder from other Emacs.app in your file system or previous installed ones.

**Comment by wyuenho** [comment]
Ah you are right. My mistake. Thanks!
